name: Continuos Integration
on: [push]
jobs: 
  format_and_test:
    runs-on: ubuntu-latest
    steps:
        
        - name: Instala o Python 3.10.6
          uses: actions/setup-python@v2
          with:
              python-version: 3.10.6
        
        - name: Realiza o checkout do repository
          uses: actions/checkout@v2

        - name: Instala Poetry
          uses: Gr1N/setup-poetry@v4

        - name: Instalar dependencias
          run: poetry install 

        - name: Format
          run: poetry run make format
        
        - name: Run tests
          run: poetry run make test

    env:
        GAETL_BD_HOST: ${{secrets.GAETL_BD_HOST}}
        GAETL_BD_PORTA: ${{secrets.GAETL_BD_PORTA}}
        GAETL_BD_NOME: ${{secrets.GAETL_BD_NOME}}
        GAETL_BD_USUARIO: ${{secrets.GAETL_BD_USUARIO}}
        GAETL_BD_SENHA: ${{secrets.GAETL_BD_SENHA}}